export const ALL_SECTIONS = [
  { id: 'getting-started',
    title: 'Getting Started',
    href: '/getting-started' },
  { id: 'fundamentals',
    title: 'React Fundamentals',
    href: '/fundamentals' },
  { id: 'examples',
    title: 'Website Examples',
    href: '/examples' },
  { id: 'features',
    title: 'Core Features',
    href: '/features' },
  { id: 'ai-development',
    title: 'AI-Assisted Development',
    href: '/ai-development' },
  { id: 'lua-engine',
    title: 'Lua Engine',
    href: '/lua-engine' },
  { id: 'data-architecture',
    title: 'Data Architecture',
    href: '/data-architecture' },
  { id: 'eslint-guide',
    title: 'ESLint Guide',
    href: '/eslint-guide' },
  { id: 'backend-guide',
    title: 'Backend Guide',
    href: '/backend-guide' },
  { id: 'docker-guide',
    title: 'Docker Guide',
    href: '/docker-guide' },
  { id: 'code-generator',
    title: 'Code Generator',
    href: '/code-generator' },
  { id: 'resources',
    title: 'Resources',
    href: '/resources' },
];
